import type { ResearchFieldContract } from "./types";

export const OFFICE_TYPE_VALUES = [
  "headquarters",
  "branch",
  "regional_hub",
  "remote_hub",
  "coworking",
  "unknown",
] as const;

export const HIRING_STATUS_VALUES = ["active", "limited", "frozen", "unknown"] as const;

export const COMPANY_SIZE_VALUES = [
  "1-10",
  "11-50",
  "51-200",
  "201-500",
  "501-1000",
  "1001-5000",
  "5001-10000",
  "10000+",
  "unknown",
] as const;

/** High-traffic company field contracts (D1 catalog). */
export const COMPANY_FIELD_CONTRACTS: ResearchFieldContract[] = [
  {
    path: "name",
    kind: "string",
    maxLength: 200,
    allowEmpty: false,
    description: "Display company name",
    aiMode: "cheap",
  },
  {
    path: "identity.legal_name",
    kind: "string",
    maxLength: 200,
    allowEmpty: true,
    description: "Legal registered name",
    aiMode: "cheap",
  },
  {
    path: "identity.brand_name",
    kind: "string",
    maxLength: 200,
    allowEmpty: true,
    description: "Brand / trading name",
    aiMode: "cheap",
  },
  {
    path: "identity.industry",
    kind: "string",
    maxLength: 80,
    allowEmpty: true,
    description: "Primary industry",
    aiMode: "cheap",
  },
  {
    path: "identity.sub_industry",
    kind: "string",
    maxLength: 80,
    allowEmpty: true,
    description: "Sub-industry",
    aiMode: "cheap",
  },
  {
    path: "identity.company_size",
    kind: "enum",
    enumValues: COMPANY_SIZE_VALUES,
    allowEmpty: true,
    description: "Company size band",
    aiMode: "cheap",
  },
  {
    path: "identity.founded_year",
    kind: "string",
    maxLength: 12,
    allowEmpty: true,
    description: "Founded year",
    aiMode: "cheap",
  },
  {
    path: "identity.website",
    kind: "url",
    allowEmpty: true,
    description: "Company website (https)",
    aiMode: "cheap",
  },
  {
    path: "identity.linkedin_company_url",
    kind: "url",
    allowEmpty: true,
    description: "LinkedIn company page URL",
    aiMode: "cheap",
  },
  {
    path: "identity.linkedin_company_id",
    kind: "string",
    maxLength: 64,
    allowEmpty: true,
    description: "LinkedIn company id",
    aiMode: "web",
  },
  {
    path: "identity.description",
    kind: "string",
    maxLength: 2000,
    allowEmpty: true,
    description: "Short company description",
    aiMode: "cheap",
  },
  {
    path: "office.country",
    kind: "string",
    maxLength: 80,
    allowEmpty: false,
    description: "Office country",
    aiMode: "none",
  },
  {
    path: "office.city",
    kind: "string",
    maxLength: 80,
    allowEmpty: true,
    description: "Office city",
    aiMode: "cheap",
  },
  {
    path: "office.label",
    kind: "string",
    maxLength: 120,
    allowEmpty: true,
    description: "Office label (e.g. Sofia HQ)",
    aiMode: "cheap",
  },
  {
    path: "office.office_type",
    kind: "enum",
    enumValues: OFFICE_TYPE_VALUES,
    allowEmpty: true,
    description: "Office type",
    aiMode: "cheap",
  },
  {
    path: "office.timezone",
    kind: "string",
    maxLength: 64,
    allowEmpty: true,
    description: "Timezone",
    aiMode: "cheap",
  },
  {
    path: "office.street_address",
    kind: "string",
    maxLength: 200,
    allowEmpty: true,
    description: "Street address",
    aiMode: "web",
  },
  {
    path: "office.address_line_2",
    kind: "string",
    maxLength: 200,
    allowEmpty: true,
    description: "Address line 2",
    aiMode: "web",
  },
  {
    path: "office.postal_code",
    kind: "string",
    maxLength: 32,
    allowEmpty: true,
    description: "Postal code",
    aiMode: "web",
  },
  {
    path: "office.region_state",
    kind: "string",
    maxLength: 80,
    allowEmpty: true,
    description: "Region / state",
    aiMode: "cheap",
  },
  {
    path: "office.formatted_address",
    kind: "string",
    maxLength: 300,
    allowEmpty: true,
    description: "Formatted address",
    aiMode: "web",
  },
  {
    path: "office.maps_url",
    kind: "url",
    allowEmpty: true,
    description: "Maps URL",
    aiMode: "web",
  },
  {
    path: "contacts.general_email",
    kind: "email",
    allowEmpty: true,
    requireSourcesToSet: true,
    description: "General email (requires source)",
    aiMode: "web",
  },
  {
    path: "contacts.hr_email",
    kind: "email",
    allowEmpty: true,
    requireSourcesToSet: true,
    description: "HR email (requires source)",
    aiMode: "web",
  },
  {
    path: "contacts.recruitment_email",
    kind: "email",
    allowEmpty: true,
    requireSourcesToSet: true,
    description: "Recruitment email (requires source)",
    aiMode: "web",
  },
  {
    path: "contacts.press_email",
    kind: "email",
    allowEmpty: true,
    requireSourcesToSet: true,
    description: "Press email (requires source)",
    aiMode: "web",
  },
  {
    path: "contacts.phone",
    kind: "string",
    maxLength: 40,
    allowEmpty: true,
    requireSourcesToSet: true,
    description: "Phone (requires source)",
    aiMode: "web",
  },
  {
    path: "contacts.phone_secondary",
    kind: "string",
    maxLength: 40,
    allowEmpty: true,
    requireSourcesToSet: true,
    description: "Secondary phone (requires source)",
    aiMode: "web",
  },
  {
    path: "contacts.careers_page_url",
    kind: "url",
    allowEmpty: true,
    description: "Careers page URL",
    aiMode: "web",
  },
  {
    path: "contacts.website",
    kind: "url",
    allowEmpty: true,
    description: "Contacts website",
    aiMode: "cheap",
  },
  {
    path: "hiring.hiring_status",
    kind: "enum",
    enumValues: HIRING_STATUS_VALUES,
    allowEmpty: true,
    description: "Hiring status",
    aiMode: "web",
  },
  {
    path: "hiring.open_roles_count_estimate",
    kind: "string",
    maxLength: 32,
    allowEmpty: true,
    description: "Open roles estimate",
    aiMode: "web",
  },
  {
    path: "hiring.typical_role_families",
    kind: "string_list",
    maxItems: 20,
    maxLength: 80,
    allowEmpty: true,
    description: "Typical role families",
    aiMode: "web",
  },
  {
    path: "hiring.employee_count_at_office",
    kind: "string",
    maxLength: 32,
    allowEmpty: true,
    description: "Employee count at office",
    aiMode: "web",
  },
  {
    path: "hiring.employee_count_company",
    kind: "string",
    maxLength: 32,
    allowEmpty: true,
    description: "Employee count company-wide",
    aiMode: "web",
  },
  {
    path: "hiring.glassdoor_rating",
    kind: "string",
    maxLength: 16,
    allowEmpty: true,
    description: "Glassdoor rating",
    aiMode: "web",
  },
  {
    path: "people",
    kind: "object_list",
    listItemKind: "person",
    maxItems: 20,
    requiresWeb: true,
    description: "People (LinkedIn URL required per row)",
    aiMode: "web",
  },
  {
    path: "linkedin_jobs",
    kind: "object_list",
    listItemKind: "linkedin_job",
    maxItems: 30,
    requiresWeb: true,
    description: "LinkedIn / careers job samples",
    aiMode: "web",
  },
  {
    path: "research.notes",
    kind: "string",
    maxLength: 4000,
    allowEmpty: true,
    description: "Research / targeting notes",
    aiMode: "none",
  },
];
