import { WEIGHTED_KEYWORD_CATEGORIES } from "../weighted-keywords";

import type { ResearchFieldContract } from "./types";

export const EMPLOYMENT_TYPE_VALUES = [
  "full_time",
  "part_time",
  "contract",
  "internship",
  "temporary",
  "unknown",
] as const;

export const REMOTE_POLICY_VALUES = [
  "onsite",
  "hybrid",
  "remote",
  "unknown",
] as const;

/** High-traffic job field contracts. */
export const JOB_FIELD_CONTRACTS: ResearchFieldContract[] = [
  {
    path: "title",
    kind: "string",
    maxLength: 200,
    allowEmpty: false,
    description: "Job title",
    aiMode: "cheap",
  },
  {
    path: "identity.title",
    kind: "string",
    maxLength: 200,
    allowEmpty: false,
    description: "Job title (identity)",
    aiMode: "cheap",
  },
  {
    path: "identity.normalized_title",
    kind: "string",
    maxLength: 200,
    allowEmpty: true,
    description: "Normalized title",
    aiMode: "cheap",
  },
  {
    path: "identity.department",
    kind: "string",
    maxLength: 120,
    allowEmpty: true,
    description: "Department",
    aiMode: "cheap",
  },
  {
    path: "identity.seniority_level",
    kind: "string",
    maxLength: 64,
    allowEmpty: true,
    description: "Seniority level",
    aiMode: "cheap",
  },
  {
    path: "identity.employment_type",
    kind: "enum",
    enumValues: EMPLOYMENT_TYPE_VALUES,
    allowEmpty: true,
    description: "Employment type",
    aiMode: "cheap",
  },
  {
    path: "identity.remote_policy",
    kind: "enum",
    enumValues: REMOTE_POLICY_VALUES,
    allowEmpty: true,
    description: "Remote policy",
    aiMode: "cheap",
  },
  {
    path: "identity.linkedin_url",
    kind: "url",
    allowEmpty: true,
    description: "LinkedIn job URL",
    aiMode: "cheap",
  },
  {
    path: "location.country",
    kind: "string",
    maxLength: 80,
    allowEmpty: true,
    description: "Job country",
    aiMode: "cheap",
  },
  {
    path: "location.city",
    kind: "string",
    maxLength: 80,
    allowEmpty: true,
    description: "Job city",
    aiMode: "cheap",
  },
  {
    path: "compensation.salary_range_text",
    kind: "string",
    maxLength: 200,
    allowEmpty: true,
    description: "Salary range text",
    aiMode: "web",
  },
  {
    path: "compensation.currency",
    kind: "string",
    maxLength: 8,
    allowEmpty: true,
    description: "Currency code",
    aiMode: "cheap",
  },
  {
    path: "compensation.benefits_summary",
    kind: "string",
    maxLength: 1000,
    allowEmpty: true,
    description: "Benefits summary",
    aiMode: "web",
  },
  {
    path: "role.raw_jd_text",
    kind: "string",
    maxLength: 50_000,
    allowEmpty: true,
    description: "Raw job description text (user paste)",
    aiMode: "none",
  },
  {
    path: "role.description_summary",
    kind: "string",
    maxLength: 3000,
    allowEmpty: true,
    description: "Role description summary",
    aiMode: "cheap",
  },
  {
    path: "role.responsibilities",
    kind: "string_list",
    maxItems: 40,
    maxLength: 400,
    allowEmpty: true,
    description: "Responsibilities",
    aiMode: "cheap",
  },
  {
    path: "role.qualifications",
    kind: "string_list",
    maxItems: 40,
    maxLength: 400,
    allowEmpty: true,
    description: "Qualifications",
    aiMode: "cheap",
  },
  {
    path: "role.nice_to_have",
    kind: "string_list",
    maxItems: 30,
    maxLength: 400,
    allowEmpty: true,
    description: "Nice to have",
    aiMode: "cheap",
  },
  {
    path: "role.reporting_to",
    kind: "string",
    maxLength: 120,
    allowEmpty: true,
    description: "Reporting to",
    aiMode: "cheap",
  },
  {
    path: "role.team_size",
    kind: "string",
    maxLength: 64,
    allowEmpty: true,
    description: "Team size",
    aiMode: "cheap",
  },
  {
    path: "skills.skills_required",
    kind: "string_list",
    maxItems: 50,
    maxLength: 80,
    allowEmpty: true,
    description: "Required skills",
    aiMode: "derived",
  },
  {
    path: "skills.skills_preferred",
    kind: "string_list",
    maxItems: 50,
    maxLength: 80,
    allowEmpty: true,
    description: "Preferred skills",
    aiMode: "derived",
  },
  {
    path: "skills.tools",
    kind: "string_list",
    maxItems: 50,
    maxLength: 80,
    allowEmpty: true,
    description: "Tools",
    aiMode: "derived",
  },
  {
    path: "skills.certifications",
    kind: "string_list",
    maxItems: 30,
    maxLength: 80,
    allowEmpty: true,
    description: "Certifications",
    aiMode: "cheap",
  },
  {
    path: "skills.languages",
    kind: "string_list",
    maxItems: 20,
    maxLength: 40,
    allowEmpty: true,
    description: "Languages",
    aiMode: "cheap",
  },
  {
    path: "weighted_keywords",
    kind: "weighted_keywords",
    maxItems: 120,
    description: "Weighted keywords (evidence-aware; D3)",
    aiMode: "derived",
  },
  {
    path: "ats.keywords",
    kind: "string_list",
    maxItems: 80,
    maxLength: 80,
    allowEmpty: true,
    description: "ATS keyword list",
    aiMode: "derived",
  },
  {
    path: "ats.action_verbs",
    kind: "string_list",
    maxItems: 40,
    maxLength: 40,
    allowEmpty: true,
    description: "ATS action verbs",
    aiMode: "derived",
  },
  {
    path: "research.notes",
    kind: "string",
    maxLength: 4000,
    allowEmpty: true,
    description: "Job research notes",
    aiMode: "none",
  },
];

/** Re-export for contract docs / prompts. */
export const JOB_KEYWORD_CATEGORIES = WEIGHTED_KEYWORD_CATEGORIES;
